package org.shortrip.boozaa.libs.ircbot;

import java.nio.charset.Charset;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.pircbotx.PircBotX;
import org.pircbotx.UtilSSLSocketFactory;
import org.pircbotx.hooks.managers.ListenerManager;

/*
*   Generated by Boozaa Bukkit Plugin Generator
*   Use it as you wish but please leave this header
*   I wish you good time develop your plugins
*   contact: boozaa@shortrip.org
*/
public class IRCBot {
  
	private PircBotX ircBot;
	protected String _server;
    protected int _port;
    protected Boolean _useSSL = false;
    protected String _chan;
    protected String _botName;
	// Logger
	private static Logger logger = Logger.getLogger("BOTIrc");
	public static void log(Level level, String message) {
		logger.log(level, "IRCBot lib - " + message);
	}
	  
	
	
	public IRCBot(String server, int port, Boolean useSSL, String chan, String botName){
        _server = server;
        _port = port;
        _useSSL = useSSL;
        _chan = chan;
        _botName = botName;

        ircBot = new PircBotX();
        //Setup this bot
        ircBot.setName(_botName); //Set the nick of the bot. CHANGE IN YOUR CODE
        ircBot.setLogin(_botName); //login part of hostmask, eg name:login@host
        ircBot.setVerbose(true); //Print everything, which is what you want to do 90% of the time
        ircBot.setAutoNickChange(true); //Automatically change nick when the current one is in use
        ircBot.setEncoding(Charset.defaultCharset());       

    }
	
	
	public ListenerManager<?> getListenerManager(){
		return ircBot.getListenerManager();
	}
	
	
	
    private Thread tInstance;
    public Thread getThread(){
        return tInstance;
    }

    public Boolean connect(){        
        if( _server.isEmpty() || _chan.isEmpty() || _botName.isEmpty() ){
            return false;
        }        
        Runnable r = new Runnable() {
            @Override
            public void run() {              
                //bot.connect throws various exceptions for failures
                try {
                    if( _useSSL ){
                        ircBot.connect(_server, _port, new UtilSSLSocketFactory().trustAllCertificates());
                    }else{
                        //Connect to the freenode IRC network
                        ircBot.connect(_server, _port);
                    }
                    //Join the channel
                    ircBot.joinChannel(_chan);                    

                } //In your code you should catch and handle each exception seperately,
                //but here we just lump them all togeather for simpliciy
                catch (Exception ex) {
                    ex.printStackTrace();
                }                
            }
        };         
        tInstance = new Thread(r);
        tInstance.start();        
        return true;        
    }


    public Boolean disconnect(){        
        ircBot.disconnect();
        tInstance.interrupt();
        return true;             
    }
    
    
    public void sendChannelMessage( String message ){
        ircBot.sendMessage(_chan, message);
    }
	
    public void sendChannelMessage( String channel, String message ){
        ircBot.sendMessage(channel, message);
    }
	
	
	
	
	public PircBotX getBot(){
        return ircBot;
    }

    public String getServerName() {
        return _server;
    }

    public int getServerPort() {
        return _port;
    }

    public Boolean isUseSSL() {
        return _useSSL;
    }

    public String getChan() {
        return _chan;
    }

    public String getBotName() {
        return _botName;
    }

    
    


	    

}
